### ISSUE TITLE
Problema ao fazer login pelo celular via Google Chrome

### ISSUE THREAD

**Issue by dsfigueiredo** [brunosantoshx/hxphp#133]
Boa tarde Bruno, venho acompanhando a serie no youtube e antes de mais nada meus parabéns pelo Framework, está muito simples e fácil de usar, claro, venho aprendendo muito desde então. 
Recentemente comecei meu primeiro projeto com este Framework mas acabei de deparando com um problema no login pelo celular. 

Quando tento fazer a autenticação a página é recarregada e volta para o login sem erros, porém quando utilizo a navegação anonima o login é realizado com sucesso. Estou utilizando os servidores da Hostgator com php 7, não tenho outro server para testar, seria algo relacionado ao meu servidor?

Quanto a autenticação pelo pc está normal, somente via celular que está acontecendo isso.

PS. não me apresenta nenhum erro, somente com login incorreto..

Desde já obrigado

**Comment by flemej** [comment]
Olá,

Você consegue rodar a aplicação do Hostgator  através do browser do PC?
Consegue fazer esse teste?


Em 06/07/2017 14:49, "dsfigueiredo" <notifications@github.com> escreveu:

Boa tarde Bruno, venho acompanhando a serie no youtube e antes de mais nada
meus parabéns pelo Framework, está muito simples e fácil de usar, claro,
venho aprendendo muito desde então.
Recentemente comecei meu primeiro projeto com este Framework mas acabei de
deparando com um problema no login pelo celular.

Quando tento fazer a autenticação a página é recarregada e volta para o
login sem erros, porém quando utilizo a navegação anonima o login é
realizado com sucesso. Estou utilizando os servidores da Hostgator com php
7, não tenho outro server para testar, seria algo relacionado ao meu
servidor?

Quanto a autenticação pelo pc está normal, somente via celular que está
acontecendo isso.

PS. não me apresenta nenhum erro, somente com login incorreto..

Desde já obrigado

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/brunosantoshx/hxphp/issues/133>, or mute the thread

**Comment by dsfigueiredo** [comment]
Olá @flemej tudo bem?

Consigo sim, no Browser do pc roda normal, o problema é apenas no celular. Ontem peguei a aplicação no meu localhost e rodei no celular, e também funcionou normalmente. Acredito que seja algo relacionado as permissões da hostgator, mas nao sei em qual arquivo setar tais permissões... saberia me dizer?

Também fiz um teste pegando o projeto da serie que @brunosantoshx fez e publiquei no meu host, e por incrível que pareça dá o mesmo problema de autenticação no celular.. já via browser no pc ou navegação anônima no celular roda normalmente.

**Comment by flemej** [comment]
Beleza cara! 
Deixa eu ver se entendi :

Então você tem uma aplicação que roda pelo browser tanto no celular quanto no PC, ou seja, não é uma apk. 
Se você roda local pelo browser do PC funciona ok. 
Se você roda local pelo browser do celular funciona ok. 
Se você roda remoto pelo browser do PC funciona ok. 
Se você roda remoto pelo browser do celular não funciona. 
Estranho... Se fosse alguma configuração no hostgator você não conseguiria rodar remoto nem mesmo do browser do PC.
O domínio dos dados é o mesmo da aplicação? Você usa CORS? 

Você consegue verificar se suas tabelas estão criadas pelo engine innodb no hostgator?

**Comment by dsfigueiredo** [comment]
Vamos lá, 

Exatamente, a aplicação roda tanto no browser do pc quanto no browser do celular, sem uso de apk, porém:

Browser no pc ok;
Browser no celular não funciona;
localhost no pc ok;
localhost no celular ok;

Resumindo, a aplicação só não funciona quando está hospedada na hostgator e com acesso via browser no celular.

Os arquivos são os mesmos, não utilizo CORS e no meu banco as tabelas estão com a engine ENGINE InnoDB porém a variável Default Storage Engine do phpMyAdmin está MyISAM.

**Comment by flemej** [comment]
Cara, acho que aí está o seu problema.
Os servidores gratuitos normalmente não oferecem suporte ao Innodb e
aparentemente o phpActiveRecord tem problemas com o MyIsam.  Penei pra
descobrir isso :)
Faz um teste... Como você não tem outro servidor, tente alterar o seu
engine local para  MyIsam e, se der pau, a saída é um servidor Innodb. Se
não der pau, ai complica! :)


Em 07/07/2017 12:07, "dsfigueiredo" <notifications@github.com> escreveu:

Vamos lá,

Exatamente, a aplicação roda tanto no browser do pc quanto no browser do
celular, sem uso de apk, porém:

Browser no pc ok;
Browser no celular não funciona;
localhost no pc ok;
localhost no celular ok;

Resumindo, a aplicação só não funciona quando está hospedada na hostgator e
com acesso via browser no celular.

Os arquivos são os mesmos, não utilizo CORS e no meu banco as tabelas estão
com a engine ENGINE InnoDB porém a variável Default Storage Engine do
phpMyAdmin está MyISAM.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/brunosantoshx/hxphp/issues/133#issuecomment-313708585>,
or mute the thread

**Comment by dsfigueiredo** [comment]
Então, tenho o xampp no meu ambiente de desenvolvimento e alterei minha engine para MyISAM e não mudou nada, em todos os dispositivos funcionou normalmente (pc x celular em ambiente local).

Se fosse algo relacionado a engine, não teria que dar problema em ambos os dispositivos?

Estava no suporte da Hostgator e cogitaram a possibilidade de ser cache do navegador, na sequencia entrei fiz a limpeza no meu celular e a aplicação funcionou normalmente. porém passando o link para alguns amigos de 4 pessoas 3 funcionou e apenas 1 não conseguiu fazer o login. Ambos acessando pela primeira vez o link.

**Comment by flemej** [comment]
Entendi, cara. Você tem razão. Se fosse o engine também não funcionaria via
browser no hostgator.
Precisamos pesquisar!!!
Agora estou meio enrolado mas também vou dar uma olhada com mais cuidado
pra ver se descubro algo.
Até mais



Em 07/07/2017 15:32, "dsfigueiredo" <notifications@github.com> escreveu:

Então, tenho o xampp no meu ambiente de desenvolvimento e alterei minha
engine para MyISAM e não mudou nada, em todos os dispositivos funcionou
normalmente (pc x celular em ambiente local).

Se fosse algo relacionado a engine, não teria que dar problema em ambos os
dispositivos?

Estava no suporte da Hostgator e cogitaram a possibilidade de ser cache do
navegador, na sequencia entrei fiz a limpeza no meu celular e a aplicação
funcionou normalmente. porém passando o link para alguns amigos de 4
pessoas 3 funcionou e apenas 1 não conseguiu fazer o login. Ambos acessando
pela primeira vez o link.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/brunosantoshx/hxphp/issues/133#issuecomment-313759497>,
or mute the thread

**Comment by flemej** [comment]
@dsfigueiredo, encontrei um cara que tem um problema muito parecido com o seu. Dá uma olhada:
https://github.com/sabnzbd/sabnzbd/issues/601

**Comment by brunosantoshx** [comment]
Fala galera, boa noite. Tudo bem?

Primeiramente, valeu pelo empenho e colaboração de sempre @flemej! Tamo junto, brother!

Agora, sobre a dúvida do @dsfigueiredo, já enfrentei o mesmo problema e subi no repositório um commit que resolvia, portanto, preciso primeiramente validar contigo se você está usando a última versão.

O que ocorre é que o serviço de autenticação gera a `login_string` com `user_id` + `username` + `IP`. Tudo certo e deveria funcionar perfeitamente em qualquer dispositivo, MAS.... O Google está trabalhando em aceleradores de páginas web para dispositivos móveis e, pra isto, proxy é utilizado. O IP usado na geração da `login_string` não é o mesmo quando o `login_check()` tenta validar por causa deste mecanismo.

Fico no aguardo dos seus comentários.
Forte abraço e sucesso sempre!
